# Generated by Django 4.0.2 on 2022-03-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastActive', models.CharField(default='08:36PM', max_length=25)),
                ('name', models.CharField(max_length=125, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('usePurpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='twousermessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=25)),
                ('messages', models.CharField(default='', max_length=512)),
                ('userFrom', models.CharField(max_length=25)),
                ('userTo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='makeFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.EmailField(max_length=255)),
                ('requested', models.EmailField(max_length=255)),
                ('status', models.TextField(default='requested', max_length=25)),
                ('bpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pare_central.baseprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FullProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImg', models.ImageField(default='user_profile/default.jpg', upload_to='user_profile')),
                ('address', models.TextField(default='not assigned', max_length=255)),
                ('city', models.TextField(default='not assigned', max_length=100)),
                ('pincode', models.IntegerField(default=0)),
                ('firstname', models.CharField(default='pare', max_length=155)),
                ('lastname', models.CharField(default='user', max_length=155)),
                ('bpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pare_central.baseprofile')),
            ],
        ),
    ]
