# Generated by Django 2.2.1 on 2022-03-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pare_central', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='baseprofile',
            name='lastActive',
            field=models.CharField(default='10:51PM', max_length=25),
        ),
        migrations.AlterField(
            model_name='fullprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='makefriends',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='twousermessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
