# Generated by Django 2.2.1 on 2022-03-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pare_central', '0006_auto_20220313_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='lastActive',
            field=models.CharField(default='12:38AM', max_length=25),
        ),
    ]
