# Generated by Django 2.2.1 on 2022-03-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pare_central', '0008_auto_20220314_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='lastActive',
            field=models.CharField(default='now', max_length=25),
        ),
    ]
